name: This will deploy the safe secure tested app on Prod server

on:
  workflow_call:
     inputs:
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to prod server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            echo "Starting deployment..."

            # go to home
            cd ~

            # pull latest image
            docker pull shubh1840/portfolio:${{ inputs.image_tag }}

            # stop old container if exists
            docker stop app || true
            docker rm app || true

            # run new container
            docker run -d \
                --name app \
                -p 80:3000 \
                shubh1840/portfolio:${{ inputs.image_tag }}

            echo "Deployment done"
