#This is the name of the workflow
name: hello

on:
  push:
    branches: [main]
    paths:
      - '**.html'
jobs:
  #This is the name of the job
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to all users
        run: echo "Hello guys"
        
      - name: introduce yourself
        run: echo "Hello $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what version of python, docker installed
        run: docker --version && python --version
